### PR TITLE
Disables branch builds for all branches except master

### PR DESCRIPTION
**Pull request by nikolaykasyanov**
We want PR builds only for all branches except master.

### CODE REVIEW

**Comment by tarbayev** [comment]
Does this mean all PR's should be into `master` from `master`?

**Comment by nikolaykasyanov** [comment]
@tarbayev it has nothing to do with PRs, it only limits the scope of regular push builds (as opposed to PR builds).

**Comment by nikolaykasyanov** [comment]
To clarify what I am trying to avoid (2nd build):

screen shot 2017-04-27 at 17 08 08

**Comment by tarbayev** [comment]
Haven't noticed travis runs separate builds for PR's. However this change would remove the ability to check your branch before creating a PR.

**Comment by nikolaykasyanov** [comment]
@tarbayev you can whitelist your branch in .travis.yml when absolutely necessary.

**Comment by nikolaykasyanov** [comment]
though I prefer to just create WIP PR early.

**Review by tarbayev — APPROVED** [review]

**Pull request merged**
